ci: Docker testing
- Adds test for API container
- Refactors Web container to read from updated dockerfile dir
- Execute on push

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -7,13 +7,59 @@ name: Test Docker Image
 
 on:
   workflow_dispatch:
+  push:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 jobs:
-  test:
+  test-api:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build Docker image
+        run: |
+          docker build \
+            -f .docker/api.dockerfile \
+            -t promptfoo-api:ci \
+            .
+
+      - name: Container health check
+        run: |
+          # Start in detached mode
+          docker run -d --name api -p 15500:15500 promptfoo-api:ci
+
+          # Loop to check if the server is up
+          for i in {1..10}; do
+            if curl -f http://localhost:15500/api/health; then
+              echo -e "\nHealth check passed"
+              HEALTH_CHECK_PASS=true
+              break
+            else
+              echo "Health check failed, retrying in 2 seconds..."
+              sleep 2
+            fi
+          done
+
+          # If health check did not pass after retries, exit with an error
+          if [ -z "$HEALTH_CHECK_PASS" ]; then
+            echo -e "\nHealth check failed after multiple attempts" >&2
+            docker stop api
+            docker rm api
+            exit 1
+          fi
+
+          # Stop and remove the Docker container
+          docker stop api
+          docker rm api
+
+  test-web:
     runs-on: ubuntu-latest
 
     steps:
@@ -24,7 +70,12 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - name: Build Docker image
-        run: docker build --build-arg NEXT_PUBLIC_PROMPTFOO_BASE_URL=http://localhost:3000 -t promptfoo-ui:ci .
+        run: |
+          docker build \
+            -f .docker/web.dockerfile \
+            --build-arg NEXT_PUBLIC_PROMPTFOO_BASE_URL=http://localhost:3000 \
+            -t promptfoo-ui:ci \
+            .
 
       - name: Run Docker container
         run: |
